// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device/traits/motion_sensor.proto

package traits

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Possible states for motion detected
type MotionDetectionState int32

const (
	// No motion is detected, or has been detected within the not_detected_delay period
	MotionDetectionState_NOT_DETECTED MotionDetectionState = 0
	// Motion has been detected by the device.
	MotionDetectionState_DETECTED MotionDetectionState = 1
)

var MotionDetectionState_name = map[int32]string{
	0: "NOT_DETECTED",
	1: "DETECTED",
}

var MotionDetectionState_value = map[string]int32{
	"NOT_DETECTED": 0,
	"DETECTED":     1,
}

func (x MotionDetectionState) String() string {
	return proto.EnumName(MotionDetectionState_name, int32(x))
}

func (MotionDetectionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{0}
}

// the current state of the motion sensor
type MotionDetection struct {
	// has motion been detected or not
	State                MotionDetectionState `protobuf:"varint,1,opt,name=state,proto3,enum=smartcore.api.device.traits.MotionDetectionState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MotionDetection) Reset()         { *m = MotionDetection{} }
func (m *MotionDetection) String() string { return proto.CompactTextString(m) }
func (*MotionDetection) ProtoMessage()    {}
func (*MotionDetection) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{0}
}

func (m *MotionDetection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionDetection.Unmarshal(m, b)
}
func (m *MotionDetection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionDetection.Marshal(b, m, deterministic)
}
func (m *MotionDetection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionDetection.Merge(m, src)
}
func (m *MotionDetection) XXX_Size() int {
	return xxx_messageInfo_MotionDetection.Size(m)
}
func (m *MotionDetection) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionDetection.DiscardUnknown(m)
}

var xxx_messageInfo_MotionDetection proto.InternalMessageInfo

func (m *MotionDetection) GetState() MotionDetectionState {
	if m != nil {
		return m.State
	}
	return MotionDetectionState_NOT_DETECTED
}

// Trait.attribute for the configuration of the device
type MotionSensorAttributes struct {
	// how long the device is configured to wait before reporting a state of NOT_DETECTED. Should default to 30 seconds.
	NotDetectedDelay     *duration.Duration `protobuf:"bytes,1,opt,name=not_detected_delay,json=notDetectedDelay,proto3" json:"not_detected_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MotionSensorAttributes) Reset()         { *m = MotionSensorAttributes{} }
func (m *MotionSensorAttributes) String() string { return proto.CompactTextString(m) }
func (*MotionSensorAttributes) ProtoMessage()    {}
func (*MotionSensorAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{1}
}

func (m *MotionSensorAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionSensorAttributes.Unmarshal(m, b)
}
func (m *MotionSensorAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionSensorAttributes.Marshal(b, m, deterministic)
}
func (m *MotionSensorAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionSensorAttributes.Merge(m, src)
}
func (m *MotionSensorAttributes) XXX_Size() int {
	return xxx_messageInfo_MotionSensorAttributes.Size(m)
}
func (m *MotionSensorAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionSensorAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_MotionSensorAttributes proto.InternalMessageInfo

func (m *MotionSensorAttributes) GetNotDetectedDelay() *duration.Duration {
	if m != nil {
		return m.NotDetectedDelay
	}
	return nil
}

// request to fetch the current state of the device
type GetMotionDetectionRequest struct {
	// the name for the device to get the detection state for
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMotionDetectionRequest) Reset()         { *m = GetMotionDetectionRequest{} }
func (m *GetMotionDetectionRequest) String() string { return proto.CompactTextString(m) }
func (*GetMotionDetectionRequest) ProtoMessage()    {}
func (*GetMotionDetectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{2}
}

func (m *GetMotionDetectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMotionDetectionRequest.Unmarshal(m, b)
}
func (m *GetMotionDetectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMotionDetectionRequest.Marshal(b, m, deterministic)
}
func (m *GetMotionDetectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMotionDetectionRequest.Merge(m, src)
}
func (m *GetMotionDetectionRequest) XXX_Size() int {
	return xxx_messageInfo_GetMotionDetectionRequest.Size(m)
}
func (m *GetMotionDetectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMotionDetectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMotionDetectionRequest proto.InternalMessageInfo

func (m *GetMotionDetectionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// request to be notified of changes to the state of the device
type PullMotionDetectionRequest struct {
	// the name for the device to subscribe to
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMotionDetectionRequest) Reset()         { *m = PullMotionDetectionRequest{} }
func (m *PullMotionDetectionRequest) String() string { return proto.CompactTextString(m) }
func (*PullMotionDetectionRequest) ProtoMessage()    {}
func (*PullMotionDetectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{3}
}

func (m *PullMotionDetectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMotionDetectionRequest.Unmarshal(m, b)
}
func (m *PullMotionDetectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMotionDetectionRequest.Marshal(b, m, deterministic)
}
func (m *PullMotionDetectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMotionDetectionRequest.Merge(m, src)
}
func (m *PullMotionDetectionRequest) XXX_Size() int {
	return xxx_messageInfo_PullMotionDetectionRequest.Size(m)
}
func (m *PullMotionDetectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMotionDetectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullMotionDetectionRequest proto.InternalMessageInfo

func (m *PullMotionDetectionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// response containing motion state changes
type PullMotionDetectionResponse struct {
	// the list of changes that have occurred since the last event
	Changes              []*MotionDetectionChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PullMotionDetectionResponse) Reset()         { *m = PullMotionDetectionResponse{} }
func (m *PullMotionDetectionResponse) String() string { return proto.CompactTextString(m) }
func (*PullMotionDetectionResponse) ProtoMessage()    {}
func (*PullMotionDetectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{4}
}

func (m *PullMotionDetectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMotionDetectionResponse.Unmarshal(m, b)
}
func (m *PullMotionDetectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMotionDetectionResponse.Marshal(b, m, deterministic)
}
func (m *PullMotionDetectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMotionDetectionResponse.Merge(m, src)
}
func (m *PullMotionDetectionResponse) XXX_Size() int {
	return xxx_messageInfo_PullMotionDetectionResponse.Size(m)
}
func (m *PullMotionDetectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMotionDetectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullMotionDetectionResponse proto.InternalMessageInfo

func (m *PullMotionDetectionResponse) GetChanges() []*MotionDetectionChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

// A change to the motion state of the device
type MotionDetectionChange struct {
	// name for the device that issued the change
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// when the change occurred
	CreateTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// the new state for the device
	MotionDetection      *MotionDetection `protobuf:"bytes,3,opt,name=motion_detection,json=motionDetection,proto3" json:"motion_detection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MotionDetectionChange) Reset()         { *m = MotionDetectionChange{} }
func (m *MotionDetectionChange) String() string { return proto.CompactTextString(m) }
func (*MotionDetectionChange) ProtoMessage()    {}
func (*MotionDetectionChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f8532ee139b030, []int{5}
}

func (m *MotionDetectionChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionDetectionChange.Unmarshal(m, b)
}
func (m *MotionDetectionChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionDetectionChange.Marshal(b, m, deterministic)
}
func (m *MotionDetectionChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionDetectionChange.Merge(m, src)
}
func (m *MotionDetectionChange) XXX_Size() int {
	return xxx_messageInfo_MotionDetectionChange.Size(m)
}
func (m *MotionDetectionChange) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionDetectionChange.DiscardUnknown(m)
}

var xxx_messageInfo_MotionDetectionChange proto.InternalMessageInfo

func (m *MotionDetectionChange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MotionDetectionChange) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *MotionDetectionChange) GetMotionDetection() *MotionDetection {
	if m != nil {
		return m.MotionDetection
	}
	return nil
}

func init() {
	proto.RegisterEnum("smartcore.api.device.traits.MotionDetectionState", MotionDetectionState_name, MotionDetectionState_value)
	proto.RegisterType((*MotionDetection)(nil), "smartcore.api.device.traits.MotionDetection")
	proto.RegisterType((*MotionSensorAttributes)(nil), "smartcore.api.device.traits.MotionSensorAttributes")
	proto.RegisterType((*GetMotionDetectionRequest)(nil), "smartcore.api.device.traits.GetMotionDetectionRequest")
	proto.RegisterType((*PullMotionDetectionRequest)(nil), "smartcore.api.device.traits.PullMotionDetectionRequest")
	proto.RegisterType((*PullMotionDetectionResponse)(nil), "smartcore.api.device.traits.PullMotionDetectionResponse")
	proto.RegisterType((*MotionDetectionChange)(nil), "smartcore.api.device.traits.MotionDetectionChange")
}

func init() { proto.RegisterFile("device/traits/motion_sensor.proto", fileDescriptor_75f8532ee139b030) }

var fileDescriptor_75f8532ee139b030 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xc7, 0x23, 0xa7, 0x9f, 0x63, 0xd3, 0xb8, 0x4b, 0x5a, 0x1c, 0x19, 0x9a, 0x54, 0xa7, 0x50,
	0xda, 0x55, 0xe2, 0x42, 0x5a, 0xe8, 0xc9, 0x89, 0x8c, 0x2f, 0xfd, 0x30, 0xb2, 0xa1, 0x10, 0x0c,
	0x66, 0x2d, 0x6d, 0xd5, 0x25, 0x96, 0x56, 0xd5, 0x8e, 0x0c, 0xed, 0x3b, 0xf4, 0x05, 0x7a, 0xef,
	0xa5, 0x6f, 0xd1, 0x6b, 0x9f, 0xaa, 0x68, 0xd7, 0x36, 0x8e, 0xa3, 0x18, 0x74, 0x93, 0x77, 0xe6,
	0x37, 0xf3, 0x9f, 0x99, 0x3f, 0x86, 0xe7, 0x21, 0x9f, 0x8b, 0x80, 0xbb, 0x98, 0x31, 0x81, 0xca,
	0x8d, 0x25, 0x0a, 0x99, 0x4c, 0x14, 0x4f, 0x94, 0xcc, 0x68, 0x9a, 0x49, 0x94, 0xa4, 0xad, 0x62,
	0x96, 0x61, 0x20, 0x33, 0x4e, 0x59, 0x2a, 0xa8, 0x01, 0xa8, 0x01, 0xec, 0x67, 0x91, 0x94, 0xd1,
	0x8c, 0xbb, 0x3a, 0x75, 0x9a, 0x7f, 0x71, 0xc3, 0x3c, 0x63, 0x45, 0x0d, 0x03, 0xdb, 0x87, 0x9b,
	0x71, 0x14, 0x31, 0x57, 0xc8, 0xe2, 0xd4, 0x24, 0x38, 0x97, 0xb0, 0xf7, 0x41, 0x37, 0xf5, 0x38,
	0xf2, 0xa0, 0xf8, 0x20, 0x7d, 0xb8, 0xab, 0x90, 0x21, 0x6f, 0x59, 0x47, 0xd6, 0xf1, 0xa3, 0xce,
	0x29, 0xdd, 0x22, 0x80, 0x6e, 0xc0, 0xc3, 0x02, 0xf4, 0x0d, 0xef, 0x30, 0x78, 0x6a, 0xc2, 0x43,
	0x3d, 0x4f, 0x17, 0x31, 0x13, 0xd3, 0x1c, 0xb9, 0x22, 0x7d, 0x20, 0x89, 0xc4, 0x49, 0xa8, 0x31,
	0x1e, 0x4e, 0x42, 0x3e, 0x63, 0xdf, 0x75, 0xbf, 0x7a, 0xe7, 0x80, 0x1a, 0xcd, 0x74, 0xa9, 0x99,
	0x7a, 0x8b, 0x99, 0xfc, 0x66, 0x22, 0xd1, 0x5b, 0x30, 0x5e, 0x81, 0x38, 0x2e, 0x1c, 0xf4, 0x39,
	0x6e, 0x88, 0xf0, 0xf9, 0xb7, 0x9c, 0x2b, 0x24, 0x04, 0xee, 0x24, 0x2c, 0x36, 0x73, 0x3c, 0xf4,
	0xf5, 0xb7, 0x73, 0x02, 0xf6, 0x20, 0x9f, 0xcd, 0x2a, 0x10, 0x57, 0xd0, 0x2e, 0x25, 0x54, 0x2a,
	0x13, 0xc5, 0xc9, 0x7b, 0xb8, 0x1f, 0x7c, 0x65, 0x49, 0xc4, 0x55, 0xcb, 0x3a, 0xda, 0x3d, 0xae,
	0x77, 0x3a, 0x55, 0xf6, 0x75, 0xa1, 0x51, 0x7f, 0x59, 0xc2, 0xf9, 0x6b, 0xc1, 0x93, 0xd2, 0x94,
	0x32, 0x69, 0xe4, 0x1d, 0xd4, 0x83, 0x8c, 0x33, 0xe4, 0x93, 0xe2, 0xac, 0xad, 0x9a, 0xde, 0x9f,
	0x7d, 0x63, 0x7f, 0xa3, 0xe5, 0xcd, 0x7d, 0x30, 0xe9, 0xc5, 0x03, 0xf9, 0x0c, 0xcd, 0x85, 0xdd,
	0xc2, 0x65, 0xab, 0xd6, 0xae, 0xae, 0xf0, 0xb2, 0xca, 0x04, 0xfe, 0x5e, 0x7c, 0xfd, 0xe1, 0xc5,
	0x19, 0xec, 0x97, 0xb9, 0x82, 0x34, 0xa1, 0xf1, 0xf1, 0xd3, 0x68, 0xe2, 0xf5, 0x46, 0xbd, 0x8b,
	0x51, 0xcf, 0x6b, 0xee, 0x90, 0x06, 0x3c, 0x58, 0xfd, 0xb2, 0x3a, 0xbf, 0x6a, 0xd0, 0x58, 0xf7,
	0x0b, 0xf9, 0x01, 0xe4, 0xe6, 0x71, 0xc9, 0xd9, 0x56, 0x75, 0xb7, 0xba, 0xc1, 0xae, 0x34, 0x15,
	0xf9, 0x69, 0xc1, 0x7e, 0xc9, 0xd9, 0x15, 0x79, 0xb3, 0xb5, 0xcc, 0xed, 0xde, 0xb2, 0xdf, 0x56,
	0x07, 0x8d, 0xc5, 0x9c, 0x9d, 0x13, 0xeb, 0xfc, 0xb7, 0x05, 0x87, 0x21, 0x9f, 0x6f, 0xab, 0x71,
	0xfe, 0x78, 0x7d, 0x7b, 0x83, 0xe2, 0xfa, 0x03, 0xeb, 0xf2, 0x34, 0x12, 0x48, 0xe7, 0x2c, 0x41,
	0x41, 0x03, 0x49, 0xf3, 0x2b, 0x77, 0x55, 0xc1, 0x55, 0xc1, 0x2b, 0x96, 0x0a, 0x37, 0x92, 0xee,
	0xb5, 0x7f, 0xa1, 0x3f, 0xb5, 0xf6, 0x70, 0xd5, 0xa5, 0x9b, 0x0a, 0xea, 0x99, 0x2e, 0x23, 0x1d,
	0xfd, 0xb7, 0x16, 0x1d, 0x77, 0x53, 0x31, 0x36, 0xd1, 0xb1, 0x89, 0x4e, 0xef, 0x69, 0xd7, 0xbd,
	0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xc9, 0x2a, 0x36, 0xd9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MotionSensorClient is the client API for MotionSensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MotionSensorClient interface {
	// Get the current motion state for the device.
	GetMotionDetection(ctx context.Context, in *GetMotionDetectionRequest, opts ...grpc.CallOption) (*MotionDetection, error)
	// subscribe to changes in the motion state for the device.
	PullMotionDetections(ctx context.Context, in *PullMotionDetectionRequest, opts ...grpc.CallOption) (MotionSensor_PullMotionDetectionsClient, error)
}

type motionSensorClient struct {
	cc *grpc.ClientConn
}

func NewMotionSensorClient(cc *grpc.ClientConn) MotionSensorClient {
	return &motionSensorClient{cc}
}

func (c *motionSensorClient) GetMotionDetection(ctx context.Context, in *GetMotionDetectionRequest, opts ...grpc.CallOption) (*MotionDetection, error) {
	out := new(MotionDetection)
	err := c.cc.Invoke(ctx, "/smartcore.api.device.traits.MotionSensor/GetMotionDetection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motionSensorClient) PullMotionDetections(ctx context.Context, in *PullMotionDetectionRequest, opts ...grpc.CallOption) (MotionSensor_PullMotionDetectionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MotionSensor_serviceDesc.Streams[0], "/smartcore.api.device.traits.MotionSensor/PullMotionDetections", opts...)
	if err != nil {
		return nil, err
	}
	x := &motionSensorPullMotionDetectionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MotionSensor_PullMotionDetectionsClient interface {
	Recv() (*PullMotionDetectionResponse, error)
	grpc.ClientStream
}

type motionSensorPullMotionDetectionsClient struct {
	grpc.ClientStream
}

func (x *motionSensorPullMotionDetectionsClient) Recv() (*PullMotionDetectionResponse, error) {
	m := new(PullMotionDetectionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MotionSensorServer is the server API for MotionSensor service.
type MotionSensorServer interface {
	// Get the current motion state for the device.
	GetMotionDetection(context.Context, *GetMotionDetectionRequest) (*MotionDetection, error)
	// subscribe to changes in the motion state for the device.
	PullMotionDetections(*PullMotionDetectionRequest, MotionSensor_PullMotionDetectionsServer) error
}

// UnimplementedMotionSensorServer can be embedded to have forward compatible implementations.
type UnimplementedMotionSensorServer struct {
}

func (*UnimplementedMotionSensorServer) GetMotionDetection(ctx context.Context, req *GetMotionDetectionRequest) (*MotionDetection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMotionDetection not implemented")
}
func (*UnimplementedMotionSensorServer) PullMotionDetections(req *PullMotionDetectionRequest, srv MotionSensor_PullMotionDetectionsServer) error {
	return status.Errorf(codes.Unimplemented, "method PullMotionDetections not implemented")
}

func RegisterMotionSensorServer(s *grpc.Server, srv MotionSensorServer) {
	s.RegisterService(&_MotionSensor_serviceDesc, srv)
}

func _MotionSensor_GetMotionDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMotionDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotionSensorServer).GetMotionDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartcore.api.device.traits.MotionSensor/GetMotionDetection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotionSensorServer).GetMotionDetection(ctx, req.(*GetMotionDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MotionSensor_PullMotionDetections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullMotionDetectionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MotionSensorServer).PullMotionDetections(m, &motionSensorPullMotionDetectionsServer{stream})
}

type MotionSensor_PullMotionDetectionsServer interface {
	Send(*PullMotionDetectionResponse) error
	grpc.ServerStream
}

type motionSensorPullMotionDetectionsServer struct {
	grpc.ServerStream
}

func (x *motionSensorPullMotionDetectionsServer) Send(m *PullMotionDetectionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MotionSensor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smartcore.api.device.traits.MotionSensor",
	HandlerType: (*MotionSensorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMotionDetection",
			Handler:    _MotionSensor_GetMotionDetection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullMotionDetections",
			Handler:       _MotionSensor_PullMotionDetections_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "device/traits/motion_sensor.proto",
}
