// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/page_token.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a specialist token used for fetching subsequent pages of a List request. Typically encoded as base64 or
// something similar.
//
// @see https://cloud.google.com/apis/design/design_patterns#list_pagination
type PageToken struct {
	// there can be only one indicator of the start of the next page
	//
	// Types that are valid to be assigned to PageStart:
	//	*PageToken_LastOffset
	//	*PageToken_LastResourceName
	PageStart            isPageToken_PageStart `protobuf_oneof:"page_start"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PageToken) Reset()         { *m = PageToken{} }
func (m *PageToken) String() string { return proto.CompactTextString(m) }
func (*PageToken) ProtoMessage()    {}
func (*PageToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_be6d07073f799b4d, []int{0}
}

func (m *PageToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageToken.Unmarshal(m, b)
}
func (m *PageToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageToken.Marshal(b, m, deterministic)
}
func (m *PageToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageToken.Merge(m, src)
}
func (m *PageToken) XXX_Size() int {
	return xxx_messageInfo_PageToken.Size(m)
}
func (m *PageToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PageToken.DiscardUnknown(m)
}

var xxx_messageInfo_PageToken proto.InternalMessageInfo

type isPageToken_PageStart interface {
	isPageToken_PageStart()
}

type PageToken_LastOffset struct {
	LastOffset int32 `protobuf:"varint,1,opt,name=last_offset,json=lastOffset,proto3,oneof"`
}

type PageToken_LastResourceName struct {
	LastResourceName string `protobuf:"bytes,2,opt,name=last_resource_name,json=lastResourceName,proto3,oneof"`
}

func (*PageToken_LastOffset) isPageToken_PageStart() {}

func (*PageToken_LastResourceName) isPageToken_PageStart() {}

func (m *PageToken) GetPageStart() isPageToken_PageStart {
	if m != nil {
		return m.PageStart
	}
	return nil
}

func (m *PageToken) GetLastOffset() int32 {
	if x, ok := m.GetPageStart().(*PageToken_LastOffset); ok {
		return x.LastOffset
	}
	return 0
}

func (m *PageToken) GetLastResourceName() string {
	if x, ok := m.GetPageStart().(*PageToken_LastResourceName); ok {
		return x.LastResourceName
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PageToken) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PageToken_LastOffset)(nil),
		(*PageToken_LastResourceName)(nil),
	}
}

func init() {
	proto.RegisterType((*PageToken)(nil), "smartcore.api.types.PageToken")
}

func init() { proto.RegisterFile("types/page_token.proto", fileDescriptor_be6d07073f799b4d) }

var fileDescriptor_be6d07073f799b4d = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x82, 0x42, 0x47, 0x11, 0x49, 0x41, 0x7b, 0xac, 0x9e, 0xea, 0xc1, 0xd9, 0x83,
	0x4f, 0x60, 0x4e, 0x3d, 0x69, 0x88, 0x3d, 0x79, 0x09, 0x63, 0x9c, 0x2e, 0x4b, 0x93, 0xcc, 0xb2,
	0x3b, 0x2d, 0xf8, 0x4a, 0x3e, 0xa5, 0xec, 0x22, 0x39, 0xf5, 0xfa, 0xff, 0xdf, 0x3f, 0x7c, 0x03,
	0x77, 0xfa, 0xe3, 0x39, 0x1a, 0x4f, 0x96, 0x5b, 0x95, 0x03, 0x8f, 0xe8, 0x83, 0xa8, 0x94, 0xcb,
	0x38, 0x50, 0xd0, 0x4e, 0x02, 0x23, 0x79, 0x87, 0x99, 0x7a, 0xec, 0x61, 0x51, 0x93, 0xe5, 0x5d,
	0xe2, 0xca, 0x07, 0xb8, 0xea, 0x29, 0x6a, 0x2b, 0xfb, 0x7d, 0x64, 0x5d, 0x15, 0xeb, 0x62, 0x73,
	0xb1, 0x9d, 0x35, 0x90, 0xc2, 0xf7, 0x9c, 0x95, 0x08, 0x65, 0x46, 0x02, 0x47, 0x39, 0x86, 0x8e,
	0xdb, 0x91, 0x06, 0x5e, 0xcd, 0xd7, 0xc5, 0x66, 0xb1, 0x9d, 0x35, 0xb7, 0xa9, 0x6b, 0xfe, 0xab,
	0x37, 0x1a, 0xb8, 0xba, 0x06, 0xc8, 0x22, 0x51, 0x29, 0x68, 0xd5, 0xc3, 0xfd, 0x37, 0x9f, 0xf0,
	0x8c, 0x48, 0x75, 0x33, 0x69, 0xd4, 0xc9, 0xb6, 0x2e, 0x3e, 0x9f, 0xac, 0x53, 0x3c, 0xd1, 0xa8,
	0x0e, 0x3b, 0xc1, 0xe3, 0xc1, 0x4c, 0x33, 0x13, 0xbb, 0x67, 0xf2, 0xce, 0x58, 0x31, 0x79, 0xfc,
	0x3b, 0x5f, 0x7e, 0x4c, 0x27, 0x5f, 0xbd, 0xc3, 0x5d, 0x4a, 0xbf, 0x2e, 0xf3, 0xdf, 0x2f, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x1e, 0x73, 0x48, 0x11, 0x01, 0x00, 0x00,
}
