// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: types/volume.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// What is the level of mute support that the speaker provides
type MuteSupport int32

const (
	// The speaker natively supports mute
	MuteSupport_MUTE_NATIVE MuteSupport = 0
	// Muting is emulated, typically by setting the gain to 0
	MuteSupport_MUTE_EMULATED MuteSupport = 1
)

// Enum value maps for MuteSupport.
var (
	MuteSupport_name = map[int32]string{
		0: "MUTE_NATIVE",
		1: "MUTE_EMULATED",
	}
	MuteSupport_value = map[string]int32{
		"MUTE_NATIVE":   0,
		"MUTE_EMULATED": 1,
	}
)

func (x MuteSupport) Enum() *MuteSupport {
	p := new(MuteSupport)
	*p = x
	return p
}

func (x MuteSupport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuteSupport) Descriptor() protoreflect.EnumDescriptor {
	return file_types_volume_proto_enumTypes[0].Descriptor()
}

func (MuteSupport) Type() protoreflect.EnumType {
	return &file_types_volume_proto_enumTypes[0]
}

func (x MuteSupport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuteSupport.Descriptor instead.
func (MuteSupport) EnumDescriptor() ([]byte, []int) {
	return file_types_volume_proto_rawDescGZIP(), []int{0}
}

// A change to the volume state
type VolumeChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the device that is the source of the change
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When the change was applied
	ChangeTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	// The new state for the change
	Volume *Volume `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *VolumeChange) Reset() {
	*x = VolumeChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_volume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeChange) ProtoMessage() {}

func (x *VolumeChange) ProtoReflect() protoreflect.Message {
	mi := &file_types_volume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeChange.ProtoReflect.Descriptor instead.
func (*VolumeChange) Descriptor() ([]byte, []int) {
	return file_types_volume_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeChange) GetChangeTime() *timestamp.Timestamp {
	if x != nil {
		return x.ChangeTime
	}
	return nil
}

func (x *VolumeChange) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

var File_types_volume_proto protoreflect.FileDescriptor

var file_types_volume_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x75, 0x6e,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a,
	0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x2a, 0x31, 0x0a, 0x0b, 0x4d,
	0x75, 0x74, 0x65, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x55,
	0x54, 0x45, 0x5f, 0x4e, 0x41, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4d,
	0x55, 0x54, 0x45, 0x5f, 0x45, 0x4d, 0x55, 0x4c, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x42, 0x61,
	0x0a, 0x13, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x0b, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x2e, 0x76, 0x61, 0x6e, 0x74, 0x69, 0x2e,
	0x63, 0x6f, 0x2e, 0x75, 0x6b, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x73, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0xaa,
	0x02, 0x0f, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_volume_proto_rawDescOnce sync.Once
	file_types_volume_proto_rawDescData = file_types_volume_proto_rawDesc
)

func file_types_volume_proto_rawDescGZIP() []byte {
	file_types_volume_proto_rawDescOnce.Do(func() {
		file_types_volume_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_volume_proto_rawDescData)
	})
	return file_types_volume_proto_rawDescData
}

var file_types_volume_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_volume_proto_goTypes = []interface{}{
	(MuteSupport)(0),            // 0: smartcore.types.MuteSupport
	(*VolumeChange)(nil),        // 1: smartcore.types.VolumeChange
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Volume)(nil),              // 3: smartcore.types.Volume
}
var file_types_volume_proto_depIdxs = []int32{
	2, // 0: smartcore.types.VolumeChange.change_time:type_name -> google.protobuf.Timestamp
	3, // 1: smartcore.types.VolumeChange.volume:type_name -> smartcore.types.Volume
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_volume_proto_init() }
func file_types_volume_proto_init() {
	if File_types_volume_proto != nil {
		return
	}
	file_types_unit_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_types_volume_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_volume_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_volume_proto_goTypes,
		DependencyIndexes: file_types_volume_proto_depIdxs,
		EnumInfos:         file_types_volume_proto_enumTypes,
		MessageInfos:      file_types_volume_proto_msgTypes,
	}.Build()
	File_types_volume_proto = out.File
	file_types_volume_proto_rawDesc = nil
	file_types_volume_proto_goTypes = nil
	file_types_volume_proto_depIdxs = nil
}
