name: trigger-documentation.yml
on:
  push:
    branches:
      - feature/SC-477_pull-from-smart-core-os.github.io

jobs:
  trigger_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: temp test github token
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.VANTI_BOT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/smart-core-os/smart-core-os.github.io/actions/workflows

      - name: trigger smart-core-os.github.io
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          github_token: ${{ secrets.VANTI_BOT }}
          owner: 'smart-core-os'
          repo: 'smart-core-os.github.io'
          workflow_file_name: 'publish.yml'
          ref: feature/SC-477_pull-from-smart-core-os.github.io
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true