name: trigger-documentation.yml
on:
  push:
    branches:
      - main

jobs:
  trigger_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: get timestamp of trigger
        id: trigger-timestamp
        uses: kaven-universe/github-action-current-date-time@v1.4.0
        with:
          format: 'YYYY-MM-DDTHH:mm:ss.SSSZ'
      - name: trigger smart-core-os.github.io
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          github_token: ${{ secrets.TRIGGER_DOC_BUILD }}
          owner: 'smart-core-os'
          repo: 'smart-core-os.github.io'
          workflow_file_name: 'publish.yml'
          client_payload: >
            {
              "src": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "commitTimestamp": "${{ steps.trigger-timestamp.outputs.time }}"
            }
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true